production:
  <<: *default
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  socket: /var/run/mysqld/mysqld.sock
  variables:
    sql_mode: TRADITIONAL