production:
  <<: *default
  username: admin
  password: p4ssw0rd
  host: host.docker.internal
  database: preciouspreemies
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  socket: /var/run/mysqld/mysqld.sock
  variables:
    sql_mode: TRADITIONAL