name: Deploy

on:
    workflow_run:
        workflows: ['Lint']
        branches: [main]
        types:
            - completed

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.17.1'
            - name: Cache npm dependencies
              uses: actions/cache@v4
              with:
                  path: '~/.npm'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm install --prefer-offline
            - name: Create SSH key.
              run: |
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts
            - name: Compress and upload.
              env:
                  ENVIRONMENT: production
              run: |
                  tar -cf - --exclude-from="excluded_build_files.txt" . | ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'tar -xf - -C ${{ secrets.APP_DIR }}'
            - name: Build and deploy.
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - run: doctl compute ssh zubairabubakar.co --ssh-command 'cd ${{ secrets.APP_DIR }}; npm install --prefer-offline; npm run build; npm run start;'
