name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2.2']
        kamal-version: ['2.2.2']
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Set up Kamal
        run: gem install kamal -v ${{ matrix.kamal-version }}

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Read metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - uses: docker/setup-buildx-action@v3
      - name: Build and deploy
        run: |
          kamal lock release
          kamal deploy
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
#
