name: Lint

on:
    push:
        paths:
            - 'app/**'
    pull_request:
        paths:
            - 'app/**'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.17.1'
            - name: Cache npm dependencies
              uses: actions/cache@v4
              with:
                  path: '~/.npm'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm install --prefer-offline
            - name: Run Tests
              run: npm run style:all
